<?php

namespace ExAdmin\ui\component\navigation\dropdown;

use ExAdmin\ui\component\common\Icon;
use ExAdmin\ui\component\Component;
use ExAdmin\ui\component\navigation\menu\Menu;
use ExAdmin\ui\component\navigation\menu\MenuItem;

/**
 * 下拉菜单
 * Class Dropdown
 * @link   https://next.antdv.com/components/dropdown-cn 下拉菜单组件
 * @method $this disabled(bool $disabled) 菜单是否禁用                                                                    boolean
 * @method $this overlayClassName(string $overlayClassName) 下拉根元素的类名称                                                string
 * @method $this overlayStyle(mixed $overlayStyle) 下拉根元素的样式                                                        object
 * @method $this overlay(mixed $menu)
 * @method $this placement(string $placement = 'bottomLeft') 菜单弹出位置：
 *                                              bottomLeft bottomCenter bottomRight topLeft topCenter topRight          string
 * @method $this trigger(mixed $trigger = ['hover']) 触发下拉的行为, 移动端不支持 hover                                        Array<click|hover|contextmenu>
 * @method $this visible(bool $visible) 菜单是否显示                                                                        boolean
 * @method static $this create($content) 创建
 * @package ExAdmin\ui\component\form\field
 */
class Dropdown extends Component
{
    /**
     * 组件名称
     * @var string
     */
    protected $name = 'ADropdown';

    protected $slot = ['overlay'];
    /**
     * @var Menu 
     */
    public $menu;


    public function __construct($content)
    {
        $this->menu = Menu::create();
        $this->content($content);
    }

    /**
     * 下拉菜单选项
     * @param mixed $content
     * @param string $icon
     * @return MenuItem
     */
    public function item($content, $icon = null)
    {
        return $this->menu->item($content, $icon);
    }

    /**
     * 追加前面
     * @param mixed $content
     * @param string $icon 图标
     * @return MenuItem
     */
    public function prepend($content, $icon = null)
    {
        $item = $this->menuItem($content, $icon);
        if(isset($this->menu->content['default'])){
            array_unshift($this->menu->content['default'],$item);
        }else{
            $this->menu->content['default'][] = $item;

        }

        return $item;
    }

    /**
     * 下拉菜单选项
     * @param mixed $content
     * @param string $icon
     * @return MenuItem
     */
    public function menuItem($content, $icon = null)
    {
        return MenuItem::create($this->menu)
            ->content($content)
            ->icon(Icon::create($icon));
    }
    /**
     * 追加尾部
     * @param mixed $content
     * @param string $icon 图标
     * @return MenuItem
     */
    public function append($content, $icon = null)
    {

        $item = $this->menuItem($content, $icon);
        if(isset($this->menu->content['default'])){
            arrau_push($this->menu->content['default'],$item);
        }else{
            $this->menu->content['default'][] = $item;
        }
        return $item;
    }
    public function jsonSerialize()
    {
        $this->overlay($this->menu);
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }
}