<?php

namespace ExAdmin\ui\component\detail;

use ExAdmin\ui\component\Component;
use ExAdmin\ui\component\grid\descriptions\Descriptions;
use ExAdmin\ui\component\grid\descriptions\DescriptionsItem;
use ExAdmin\ui\support\Arr;

/**
 * @method static $this create($data) 创建
 */
class Detail extends Descriptions
{
    /**
     * @var array
     */
    protected $item = [];
    /**
     * 数据源
     * @var array
     */
    protected $data = [];

    public function __construct($data)
    {
        $this->data = $data;
        $this->column(['xxl'=> 4, 'xl'=> 3, 'lg'=> 3, 'md'=> 3, 'sm'=> 2, 'xs'=> 1]);
        parent::__construct();
    }

    /**
     * 添加一个item
     * @param string $field 字段
     * @param string|Component $label 内容的描述
     * @return Item
     */
    public function item($field = null, $label = null)
    {
        $item = new Item($field,$label,$this->data);
        $this->push($item);
        return $item;
    }

    public function push($item)
    {
        $this->item[] = $item;
    }

    /**
     * 获取数据
     * @param string|null $field 字段
     * @return array|mixed
     */
    public function getData(string $field = null)
    {
        if (is_null($field)) {
            return $this->data;
        }
        return Arr::get($this->data, $field);
    }
    public function collectColumns(\Closure $closure)
    {
        $offset = count($this->item);
        call_user_func($closure, $this);
        $items = array_slice($this->item, $offset);
        $this->item = array_slice($this->item, 0, $offset);
        return $items;
    }
    public function jsonSerialize()
    {
        $this->content($this->item);
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }
}
