<?php

namespace ExAdmin\ui\component\detail;

use ExAdmin\ui\component\grid\descriptions\DescriptionsItem;
use ExAdmin\ui\support\Arr;

class Item extends DescriptionsItem
{
    protected $data = [];

    protected $field;

    protected $closure = null;

    protected $default = '--';
    public function __construct($field, $label, $data)
    {
        $this->data = $data;
        $this->field = $field;
        $this->label($label);
        parent::__construct();
    }

    /**
     * 设置缺失值
     * @param $value
     */
    public function default($value){
        $this->default = $value;
    }
    /**
     * 自定义显示
     * @param \Closure $closure
     * @return $this
     */
    public function display(\Closure $closure)
    {
        $this->closure = $closure;
        return $this;
    }

    public function jsonSerialize()
    {
        if(is_null($this->field)){
            $originValue =null;
        }else{
            $originValue = Arr::get($this->data, $this->field);
        }
        if (is_null($originValue)) {
            $value = $this->default;
        } else {
            $value = $originValue;
        }
        //自定义内容显示处理
        if (!is_null($this->closure)) {
            $value = call_user_func_array($this->closure, [$originValue, $this->data]);
        }
        $this->content($value);
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }
}
