<?php
/**
 * Created by PhpStorm.
 * User: rocky
 * Date: 2022-05-23
 * Time: 21:05
 */

namespace ExAdmin\ui\component\echart;

use ExAdmin\ui\component\Component;
use Hisune\EchartsPHP\ECharts;

/**
 * Class Echart
 * @package ExAdmin\ui\component\echart
 * @method $this width(string $width)  宽度
 * @method $this height(string $height = '350px')  高度
 */
class Echart extends Component
{
    protected $name = 'ExEchart';
    /**
     * @var ECharts
     */
    public $echart;

    public function __construct()
    {
        parent::__construct();
        $this->echart = new ECharts();
    }

    /**
     * 选项参数
     * @param mixed $options
     * @return $this
     */
    public function options($options){
        if($options instanceof \Closure){
            call_user_func($options,$this->echart);
            $options = $this->echart->getOption();
        }elseif (is_string($options)){
            $options = preg_replace(["/([a-zA-Z_]+[a-zA-Z0-9_]*)\s*:/", "/:\s*'(.*?)'/"], ['"\1":', ': "\1"'], $options);
            $options = json_decode($options,true);
        }
        $this->echart->_options = array_merge($this->echart->_options,$options);
        return $this;
    }
    
    public function jsonSerialize()
    {
        $this->attr('options',$this->echart->getOption());
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }
}