<?php

namespace ExAdmin\ui\component\form\field;

use ExAdmin\ui\component\form\Field;
use ExAdmin\ui\component\form\FormItem;

/**
 * 显示html
 */
class Descriptions extends Field
{
    protected $name = 'ExDescriptions';
    public function setFormItem(FormItem $formItem)
    {
        parent::setFormItem($formItem); // TODO: Change the autogenerated stub
        $this->exceptField($this->field);
    }
}