<?php

namespace ExAdmin\ui\component\grid;
use ExAdmin\ui\component\grid\grid\Column;
use ExAdmin\ui\component\grid\Table;
use ExAdmin\ui\component\navigation\Pagination;

/**
 * @method static $this create($data = []) 创建
 */
class Grid extends Table
{
    protected $name = 'ExGrid';
    /**
     * @var Column
     */
    protected $column = [];
    /**
     * @var Column
     */
    protected $childrenColumn = [];
    /**
     * @var Pagination
     */
    protected $pagination;



    protected $data = [];

    public function __construct($data = [])
    {
        $this->pagination = Pagination::create();
        $this->data = $data;
        parent::__construct();
    }
    /**
     * 添加表格列
     * @param string|\Closure $field 字段
     * @param string $label 显示的标题
     * @return Column
     */
    public function column($field, $label = '')
    {

        $childrenColumns = [];
        if ($field instanceof \Closure) {
            $prop = 'group' . md5($label . time());
            $childrenColumns = $this->collectColumns($field);
            $column = new Column($prop, $label, $this);
            $column->attr('children', array_column($childrenColumns, 'attribute'));
            foreach ($childrenColumns as $childrenColumn) {
                $childrenColumn->attr('children_row', true);
                $this->childrenColumn[] = $childrenColumn;
            }
        } else {
            $column = new Column($field, $label, $this);
        }
        $this->column[] = $column;

        return $column;
    }
    /**
     * 关闭分页
     * @param bool $bool
     */
    public function hidePage(bool $bool = true)
    {
        $this->attr('hidePage',$bool);
    }
    /**
     * 分页组件
     * @return Pagination
     */
    public function pagination()
    {
        return $this->pagination;
    }
    public function collectColumns(\Closure $closure)
    {
        $offset = count($this->column);
        call_user_func($closure, $this);
        $columns = array_slice($this->column, $offset);
        $this->column = array_slice($this->column, 0, $offset);
        return $columns;
    }
    protected function parseColumn($data){
        $columns = array_merge($this->column, $this->childrenColumn);
        $tableData = [];
        foreach ($data as $key=>$row){
            $rowData = ['ex_admin_id'=>$key];
            foreach ($columns as $column) {
                $field = $column->attr('dataIndex');
                $rowData[$field] = $column->row($row);
            }
            $tableData[] = $rowData;
        }
        return $tableData;
    }
    public function jsonSerialize()
    {
        $this->attr('pagination', $this->pagination);
        $data = $this->parseColumn($this->data);
        $this->attr('dataSource',$data);
        $this->attr('columns', array_column($this->column, 'attribute'));
        return parent::jsonSerialize(); // TODO: Change the autogenerated stub
    }
}
