<?php

namespace ExAdmin\ui\component\form\field\upload;

use ExAdmin\laravel\Controllers\AttachmentController;
use ExAdmin\ui\component\form\FormItem;
use ExAdmin\ui\Route;

class File extends Upload
{
    public $uploadField;
    public function __construct($field = null, $value = '')
    {
        parent::__construct($field, $value);
        $this->progress(false);
        $this->onlyShow(false);
        $grid = Route::dispatch(AttachmentController::class,'index');
        $grid->selectionField('url');
        $this->attr('finder',$grid);
    }

    public function setFormItem(FormItem $formItem)
    {
        parent::setFormItem($formItem); // TODO: Change the autogenerated stub
        $this->action($this->formItem->form()->attr('url'));
        $this->uploadField = $this->getValidateField();
        $this->params(['upload_field' => $this->uploadField, 'ex_admin_action' => 'upload']);
    }
}
